#!/bin/bash

sudo sed -i 's/ftp.uk.debian.org/http.debian.net/' /etc/apt/sources.list
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get autoremove
sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y git php5-cli
git config --global user.name "Dave Potts"
git config --global user.email dave@goopot.co.uk
git config --global credential.helper cache
git config --global credential.helper 'cache --timeout=36000'



